---
# tasks file for tomcat_setup_check
- name: Sleep for 90 seconds and continue with play
  wait_for: timeout=90
- name: install the latest version of Docker
  yum:
    name: docker
    state: latest
    
- name: Start & Enable docker
  systemd:
      name: docker
      state: started
      enabled: true
