      
- name: Validate the sudoers file before saving
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
    create: yes
    
    
- name: Run .bash_profile
  shell:
      cp /tmp/Jenkins_ansibe_role/jenkins_setup/.bash_profile /root
      source ~/.bash_profile
    
