- name: 
  shell:
      echo  'JAVA_HOME=/usr/lib/jvm/java-11-openjdk-11.0.16.0.8-1.amzn2.0.1.x86_64' >> ~/.bash_profile
      
      echo 'export JAVA_HOME' >> ~/.bash_profile
      
      echo 'M2_HOME=/opt/apache-maven-3.8.7' >> ~/.bash_profile
      
      echo 'M2=/opt/apache-maven-3.8.7/bin' >> ~/.bash_profile
      
      echo 'export M2_HOME' >> ~/.bash_profile
      
      echo  'export M2' >> ~/.bash_profile
      
      echo 'PATH=$JAVA_HOME:$M2_HOME:$M2' >> ~/.bash_profile

      source ~/.bash_profile
